### ISSUE TITLE
The program crashes.

### ISSUE THREAD

**Issue by maskelihileci** [hfiref0x/WubbabooMark#5]
The program crashes in this section.

![image](https://github.com/hfiref0x/WubbabooMark/assets/41159853/583bf8a5-982b-4237-b46a-ca20d3447a81)

**Comment by hfiref0x** [comment]
Does it crash outside your debugger too? What is your exact Windows version and build?

**Comment by maskelihileci** [comment]
Windows 10 1607

It crashes whether the debugger is active or not.

**Comment by maskelihileci** [comment]
I used the ready-made compilation in .bin, I did not compile it myself.

**Comment by hfiref0x** [comment]
The NtUser scan method used in this detection method does not support anything below Win10 RS4 (1803) that is why it crashed for you. On pre RS4 UserHandleTable was organized differently with different structures fields and their meaning. Uncheck this scan method in program options.

**Comment by maskelihileci** [comment]
If you compile it yourself, you can certainly turn off the features, but I think it would be better to add Windows version control and enable the feature to be triggered accordingly.

**Comment by hfiref0x** [comment]
The methods are configurable through GUI. Go to menu "Probes -> Settings". This one failing for you named "Enumerate NtUser Objects". Version control is not quite realible since this software will be running in aggressive environment that is trying to fabricate vital system information such as win version and build. However I will add some exceptional checking here, thanks.

**Comment by maskelihileci** [comment]
We cannot do that because scanning starts the moment we run the application. It is not possible for us to access those settings before the entire scan is completed, and the application crashes

**Comment by hfiref0x** [comment]
Ok, I will add something more regarding this.
